spacy:
  # note that the spacy models have to be installed in the env to use it! (docker!)
  model_dir: ${oc.env:SPACY_MODELS_DIR, /spacy_models}
  models:
    en: en_core_web_trf-3.8.0
    de: de_core_news_lg-3.8.0
    it: it_core_news_lg-3.8.0
    default: en

  device: cpu
  max_text_length: 2000000 # in characters (1000000 is spaCy default)

  deployment:
    ray_actor_options:
      num_gpus: 0.
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1

whisper:
  model: base
  device: cpu
  options:
    word_timestamps: True
    beam_size: 5
    best_of: 5
    batch_size: 8

  deployment:
    ray_actor_options:
      num_gpus: .0
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1

detr:
  model: "facebook/detr-resnet-101"
  device: cpu
  deployment:
    ray_actor_options:
      num_gpus: .0
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1
  object_detection:
    confidence_threshold: 0.75
    coco2017_labels:
      # This has to be in order!!! (for object detection with DETR)
      - "background"
      - "person"
      - "bicycle"
      - "car"
      - "motorcycle"
      - "airplane"
      - "bus"
      - "train"
      - "truck"
      - "boat"
      - "traffic light"
      - "fire hydrant"
      - "street sign"
      - "stop sign"
      - "parking meter"
      - "bench"
      - "bird"
      - "cat"
      - "dog"
      - "horse"
      - "sheep"
      - "cow"
      - "elephant"
      - "bear"
      - "zebra"
      - "giraffe"
      - "hat"
      - "backpack"
      - "umbrella"
      - "shoe"
      - "eye glasses"
      - "handbag"
      - "tie"
      - suitcase
      - frisbee
      - skis
      - snowboard
      - sports ball
      - kite
      - baseball bat
      - baseball glove
      - skateboard
      - surfboard
      - tennis racket
      - bottle
      - plate
      - wine glass
      - cup
      - fork
      - knife
      - spoon
      - bowl
      - banana
      - apple
      - sandwich
      - orange
      - broccoli
      - carrot
      - hot dog
      - pizza
      - donut
      - cake
      - chair
      - couch
      - potted plant
      - bed
      - mirror
      - dining table
      - window
      - desk
      - toilet
      - door
      - tv
      - laptop
      - mouse
      - remote
      - keyboard
      - cell phone
      - microwave
      - oven
      - toaster
      - sink
      - refrigerator
      - blender
      - book
      - clock
      - vase
      - scissors
      - teddy bear
      - hair drier
      - toothbrush

clip:
  text_encoder:
    model: "sentence-transformers/clip-ViT-B-32-multilingual-v1"
    batch_size: 32
    device: cpu
  image_encoder:
    model: "clip-ViT-B-32"
    batch_size: 32
    device: cpu
  deployment:
    ray_actor_options:
      num_gpus: .0
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1

cota:
  model: "sentence-transformers/paraphrase-mpnet-base-v2"
  batch_size: 16
  device: cpu
  deployment:
    ray_actor_options:
      num_gpus: .0
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1
  root_dir: /tmp/dats/ray/cota

quote:
  model: "fynnos/quotect-mt5-base"
  max_length: 4096
  num_beams: 1
  device: cpu
  deployment:
    ray_actor_options:
      num_gpus: .0
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1

glotlid:
  model: "cis-lmu/glotlid"
  version: "latest"
  # the device is always CPU!
  deployment:
    ray_actor_options:
      num_gpus: .0
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1

coref:
  model_de: "fynnos/maverick-mes-de10"
  device: cpu
  deployment:
    ray_actor_options:
      num_gpus: .0
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1

docling:
  # scaling factor for images extracted from PDFs
  image_resolution_scale: 3.0
  # pages per PDF chunk
  max_pages_per_pdf_chunk: 10
  # tmp directory for docling
  tmp_dir: /tmp/dats/ray/docling
  deployment:
    ray_actor_options:
      num_gpus: .0
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1

promptembedder:
  model: "intfloat/multilingual-e5-large-instruct"
  max_seq_length: 512
  batch_size: 8
  device: cpu
  deployment:
    ray_actor_options:
      num_gpus: .0
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1
  root_dir: /tmp/dats/ray/promptembedder
