spacy:
  # note that the spacy models have to be installed in the env to use it! (docker!)
  models:
    en: /spacy_models/en_core_web_trf-3.6.1
    de: /spacy_models/de_core_news_lg-3.6.0
    it: /spacy_models/it_core_news_lg-3.6.0
    default: en

  device: cpu # FIXME currently only cpu is supported due to spacy limitations
  max_text_length: 2000000 # in characters (1000000 is spaCy default)

  deployment:
    ray_actor_options:
      num_gpus: 0.
      # num_cpus: 1
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1

whisper:
  model: base
  device: cpu
  options:
    beam_size: 5
    best_of: 5

  deployment:
    ray_actor_options:
      num_gpus: .0
      # num_cpus: 1
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1

detr:
  model: "facebook/detr-resnet-101"
  device: cpu
  deployment:
    ray_actor_options:
      num_gpus: .0
      # num_cpus: 1
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1
  object_detection:
    confidence_threshold: 0.75
    coco2017_labels:
      # This has to be in order!!! (for object detection with DETR)
      - "background"
      - "person"
      - "bicycle"
      - "car"
      - "motorcycle"
      - "airplane"
      - "bus"
      - "train"
      - "truck"
      - "boat"
      - "traffic light"
      - "fire hydrant"
      - "street sign"
      - "stop sign"
      - "parking meter"
      - "bench"
      - "bird"
      - "cat"
      - "dog"
      - "horse"
      - "sheep"
      - "cow"
      - "elephant"
      - "bear"
      - "zebra"
      - "giraffe"
      - "hat"
      - "backpack"
      - "umbrella"
      - "shoe"
      - "eye glasses"
      - "handbag"
      - "tie"
      - suitcase
      - frisbee
      - skis
      - snowboard
      - sports ball
      - kite
      - baseball bat
      - baseball glove
      - skateboard
      - surfboard
      - tennis racket
      - bottle
      - plate
      - wine glass
      - cup
      - fork
      - knife
      - spoon
      - bowl
      - banana
      - apple
      - sandwich
      - orange
      - broccoli
      - carrot
      - hot dog
      - pizza
      - donut
      - cake
      - chair
      - couch
      - potted plant
      - bed
      - mirror
      - dining table
      - window
      - desk
      - toilet
      - door
      - tv
      - laptop
      - mouse
      - remote
      - keyboard
      - cell phone
      - microwave
      - oven
      - toaster
      - sink
      - refrigerator
      - blender
      - book
      - clock
      - vase
      - scissors
      - teddy bear
      - hair drier
      - toothbrush

vit_gpt2:
  model: "nlpconnect/vit-gpt2-image-captioning"
  device: cpu
  image_captioning:
    max_caption_length: 16
    num_beams: 4
  deployment:
    ray_actor_options:
      num_gpus: .0
      # num_cpus: 1
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1

clip:
  text_encoder:
    model: "sentence-transformers/clip-ViT-B-32-multilingual-v1"
    batch_size: 32
    device: cpu
  image_encoder:
    model: "clip-ViT-B-32"
    batch_size: 32
    device: cpu
  deployment:
    ray_actor_options:
      num_gpus: .0
      # num_cpus: 1
    autoscaling_config:
      min_replicas: 1
      max_replicas: 1
